twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        website:
            name: 'ePortfolio+'
        button:
            create: 'Créer'
            update: 'Modifier'
            delete: 'Supprimer'
            validate: 'Valider'
            add: 'Ajouter'
            resend: 'Renvoyer'
            close: 'Fermer'
            hide: 'Masquer'
            unhide: 'Démasquer'
        navbar:
            projects: 'Projets'
            new: 'Nouveau'
            career: 'Parcours'
            profile: 'Profil'
        tab:
            project:
                new: 'Créer un nouveau projet'
            career:
                new: 'Créer un nouveau parcours'
            update: 'Mise à jour'
            details: 'Détails'
            about: 'Présentation'
            contact: 'Me Contacter'
            profile: 'Profil'
            connection: 'Connexion'
            register: 'Inscription'
