twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        website:
            name: 'E-Porfolio'
        button:
            create: 'Créer'
            update: 'Modifier'
            delete: 'Supprimer'
            validate: 'Valider'
            add: 'Ajouter'
        navbar:
            projects: 'Projets'
            new: 'Nouveau'
            career: 'Parcours'
            home: 'Accueil'
        tab:
            project:
                new: 'Créer un nouveau projet'
            career:
                new: 'Créer un nouveau parcours'
            update: 'Mise à jour'
            details: 'Détails'
            about: 'Présentation'
            contact: 'Me Contacter'
            profil: 'Profil'
            connection: 'Connexion'
            register: 'Inscription'
