### HOME ###
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

### PROJECT ###
app_project:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/project
    controller: App\Controller\ProjectController::index
    methods: GET

app_project_show:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/project/{id<[0-9]+>}
    controller: App\Controller\ProjectController::show
    methods: GET

app_project_create:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/project/create
    controller: App\Controller\ProjectController::create
    methods: GET|POST

app_project_update:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/project/{id<[0-9]+>}/update
    controller: App\Controller\ProjectController::update
    methods: GET|PUT

app_project_delete:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/project/{id<[0-9]+>}
    controller: App\Controller\ProjectController::delete
    methods: DELETE

app_image_delete:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/image/{id<[0-9]+>}
    controller: App\Controller\ProjectController::deleteImage
    methods: DELETE

### CAREER ###
app_career:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/career
    controller: App\Controller\CareerController::index
    methods: GET

app_career_create:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/career/create
    controller: App\Controller\CareerController::create
    methods: GET|POST

app_career_update:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/career/{id<[0-9]+>}/update
    controller: App\Controller\CareerController::update
    methods: GET|PUT

app_career_delete:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/career/{id<[0-9]+>}
    controller: App\Controller\CareerController::delete
    methods: DELETE

### LOGIN ###
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET

### USER ###
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST

app_resend:
    path: /resend
    controller: App\Controller\RegistrationController::sendVerificationEmail
    methods: GET

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    methods: GET

app_user:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}
    controller: App\Controller\UserController::index
    methods: GET

app_user_update:
    path: /{externalId<[0-9A-Za-zÀ-ȕ_-]+>}/user/update
    controller: App\Controller\UserController::update
    methods: GET|PUT

app_avatar_upload:
    path: /avatar/upload
    controller: App\Controller\UserController::avatarUpload
    methods: POST

