### HOME ###
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

### PROJECT ###
app_project:
    path: /project
    controller: App\Controller\ProjectController::index
    methods: GET

app_project_show:
    path: /project/{id<[0-9]+>}
    controller: App\Controller\ProjectController::show
    methods: GET

app_project_create:
    path: /project/create
    controller: App\Controller\ProjectController::create
    methods: GET|POST

app_project_update:
    path: /project/{id<[0-9]+>}/update
    controller: App\Controller\ProjectController::update
    methods: GET|PUT

app_project_delete:
    path: /project/{id<[0-9]+>}
    controller: App\Controller\ProjectController::delete
    methods: DELETE

app_image_delete:
    path: /image/{id<[0-9]+>}
    controller: App\Controller\ProjectController::deleteImage
    methods: DELETE

### CAREER ###
app_career:
    path: /carrer
    controller: App\Controller\CareerController::index
    methods: GET

app_career_create:
    path: /carrer/create
    controller: App\Controller\CareerController::create
    methods: GET|POST

app_career_update:
    path: /carrer/{id<[0-9]+>}/update
    controller: App\Controller\CareerController::update
    methods: GET|PUT

app_career_delete:
    path: /career/{id<[0-9]+>}
    controller: App\Controller\CareerController::delete
    methods: DELETE

### LOGIN ###
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET

### USER ###
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    methods: GET

app_user_show:
    path: /user
    controller: App\Controller\UserController::show
    methods: GET

app_user_update:
    path: /user/update
    controller: App\Controller\UserController::update
    methods: GET|PUT