### HOME ###
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

### PROJECT ###
app_project:
    path: /project
    controller: App\Controller\ProjectController::index
    methods: GET

app_project_show:
    path: /project/{id<[0-9]+>}
    controller: App\Controller\ProjectController::show
    methods: GET

app_project_create:
    path: /project/create
    controller: App\Controller\ProjectController::create
    methods: GET|POST

app_project_update:
    path: /project/{id<[0-9]+>}/update
    controller: App\Controller\ProjectController::update
    methods: GET|PUT

app_project_delete:
    path: /project/{id<[0-9]+>}
    controller: App\Controller\ProjectController::delete
    methods: DELETE

app_image_delete:
    path: /image/{id<[0-9]+>}
    controller: App\Controller\ProjectController::deleteImage
    methods: DELETE

### CAREER ###
app_career:
    path: /carrer
    controller: App\Controller\CareerController::index
    methods: GET

app_career_create:
    path: /carrer/create
    controller: App\Controller\CareerController::create
    methods: GET|POST

app_career_update:
    path: /carrer/{id<[0-9]+>}/update
    controller: App\Controller\CareerController::update
    methods: GET|PUT

app_career_delete:
    path: /career/{id<[0-9]+>}
    controller: App\Controller\CareerController::delete
    methods: DELETE

### USER ###
app_user:
    path: /user
    controller: App\Controller\UserController::index
    methods: GET